---
title: "MXB348 Question 1"
author: "Sebastian"
date: "2026-09-02"
output: html_document
---
```{r}
### Conditions
### Only data from return visits are used (session_id>0)
### All data regardless of final conversion or non-conversion will be used
### I = 1x9
### MRn = 9x9
```

```{r setup, include=FALSE}
setwd("D:/MXB348 - Work Integrated Learning")
customer_journey <- read.csv("D:/MXB348 - Work Integrated Learning/data/customer_journey-4.csv"); 
results <- read.csv("D:/MXB348 - Work Integrated Learning/data/results-3.csv")
### Setting the working directory and opening the files
```

```{r}
install.packages(c(
  "tidyverse",
  "markovchain",
  "expm"
))
### Download relevant files
```

```{r}
library(tidyverse)
library(markovchain)
library(expm)
### Load the relevant libraries
```

```{r}
head(customer_journey)
head(results)
str(customer_journey)
str(results)
summary(customer_journey)
summary(results)
# Displays a brief summary
```

```{r}
journeys <- customer_journey %>%
  left_join(
    results,
    by = c("user_id", "session_id")
  );
journeys <- journeys %>%
  arrange(
    user_id,
    session_id,
    order
  )

set.seed(348)

journeys <- journeys %>%
  group_by(user_id) %>%
  filter(runif(1) < 0.8) %>%
  ungroup()
### Concatenation and rearrangement of both files to have a complete 
### understanding of a users session
### Note, the use of the sequential operator over another pipeline 
```

```{r}
#  Opens viewing portal
nrow(customer_journey)
nrow(journeys)
# Debugging point, ensures equivalent dimensions
```

```{r}
transitions <- journeys %>%
  filter(session_id>0)%>% # Filters to only RETURN SESSIONS.
  group_by(user_id, session_id) %>% # Each unique combination
  arrange(order, .by_group = TRUE) %>% # Ensures ordinal categorization
  mutate(
    next_state = lead(channel) # Looks one row ahead and puts that value into a
  ) %>% # new column called "next state"
  ungroup();# Un-magnifying
transitions <- transitions %>%
  mutate(
    next_state = case_when(
      !is.na(next_state) ~ next_state, # "na" are now converted to
      conversion == 1 ~ "Conversion",
      conversion == 0 ~ "No Conversion" 
    ) # Conversion's now act as an absorbing state in a Markov Chain.
  ) # To symbolize the end of an individual tracked session.
transitions %>%
    select(
      user_id,
      session_id,
      order,
      channel,
      next_state,
      conversion
    )
### Formalizing the Markov-chain transformation mechanism (Markov Property), 
### by identifying what channel each customer moves to next.
```

```{r}
MRn_counts <- transitions %>%
  count(
    channel,
    next_state,
    name = "n"
  ) 
### This is the point in which we can begin to really interpret our data. Since
### now we have sample count data associated with each possible unique tracked 
### transition for every person and each of their sessions. 
```

```{r}
MRn_probs <- MRn_counts %>%
  group_by(channel) %>%
  mutate(
    probability = n / sum(n)
  ) %>%
  ungroup() %>%
  filter(next_state != "No Conversion")
### Converts the count data into probabilities
```

```{r}
MRn_probs %>%
  filter(next_state == "Conversion") %>%
  arrange(desc(probability))
### A tibble that shows the probability given the sample data of each channel
### turning into a conversion.
```

```{r}
states <- sort(
  unique(
    c(
      transitions$channel,
      transitions$next_state
    )
  )
);
states <- states[states != "No Conversion"]
MRn <- matrix(
  0,
  nrow = length(states),
  ncol = length(states),
  dimnames = list(states, states) # a R^(9x9) matrix with 
) # [channel no conversion conversion].
### This is all to create an empty/unfilled transition probability matrix where 
### after this section we will fill it with data that satisfy the necessary 
### properties (Square matrix with probabilities that sum to 1).
```

```{r}
for (i in seq_len(nrow(MRn_probs))) {

  from <- MRn_probs$channel[i]
  to   <- MRn_probs$next_state[i]

  MRn[from, to] <-
    MRn_probs$probability[i]
};
MRn["Conversion", ] <- 0
MRn["Conversion", "Conversion"] <- 1
```

```{r}
View(MRn)
### We have now constructed our first-order Markov Chain transition probability
### matrix. We have also got a probability of 1 in both the "No Conversion" and
### "Conversion" diagonal to represent them as absorbing states that symbolize
### how at the end of every session, we end up with either a successful or 
### unsuccessful conversion.
### Instagram has the highest observed immediate transition probability 
### conversion at approximately 25.64% with YouTube being the lowest at 25.09%.
```

```{r}
### Construction of the Initial State Vector (1x9)
states_1by9 <- c(
  "Direct",
  "Email Marketing",
  "Facebook",
  "Google Display",
  "Google Search",
  "Instagram",
  "Organic",
  "Youtube",
  "Conversion"
)

I <- journeys %>%
  filter(order == 0) %>%
  count(channel, name = "n") %>%
  complete(channel = states_1by9, fill = list(n = 0)) %>%
  mutate(n = n / sum(n))

view(I)
### This is just a way to see the initial vector in which given the sampling
### seed and training data vs testing data ratio (80/20 in our case), provides
### an initial proportional state of every channel.
```

```{r}
results <- data.frame()

for (n in 0:10) { # Starting at n = 0 is a design choice to be able to see 
  # the starting state, "I" and then the subsequent change to "I %*% Mr^n".
  result <- as.numeric(I$n %*% (MRn %^% n))
  
  results <- rbind(
    results,
    data.frame(
      n = n,
      channel = colnames(MRn),
      probability = result
    )
  )
}
### Essentially formatting and calculating each of the data points in the final
### "Probabilistic_Transitions_Plot" after the vector and matrix multiplications

### Constructing the non-conversion variable as a function of "1 - Conversion"
### at each step of n.
non_conversion <- results %>%
  filter(channel == "Conversion") %>%
  mutate(
    channel = "Non Conversion",
    probability = 1 - probability
  )

results <- bind_rows(results, non_conversion)
### finally combining the non-conversion calculations to the results data points
```

```{r}
### GG Plot
### Post calculations and primarily data visualization code to see the relevant
### transition probabilistic changes at different states of n. 
Probabilistic_Transitions_Plot <- ggplot(results, aes(
  x = n,
  y = probability,
  colour = channel,
  group = channel
)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  scale_x_continuous(
    breaks = 1:10
  ) +
  scale_y_continuous(
    limits = c(0, 1),
    breaks = seq(0, 1, 0.1)
  ) +
  labs(
    x = "Markov State Step (n)",
    y = "Probability",
    colour = "Channel"
  ) +
  theme_minimal()

Probabilistic_Transitions_Plot
```

